import * as z from "zod";

export const $ReadingKey = z.object({
  device_id: z.string(),
  sensor_id: z.string(),
  time: z.coerce.date(),
});

export const $Readings = {
  zigbee_temp: $ReadingKey.extend({
    temperature: z.number(),
    humidity: z.number(),
    battery: z.number(),
    voltage: z.number(),
  }),
  zigbee_occupancy: $ReadingKey.extend({
    occupancy: z.boolean(),
    illuminance: z.number(),
    battery: z.number(),
    voltage: z.number(),
  }),
  zigbee_contact: $ReadingKey.extend({
    contact: z.boolean(),
    battery: z.number(),
    voltage: z.number(),
  }),
  zigbee_power: $ReadingKey.extend({
    state: z.string().nullish(),
    power: z.number(),
    battery: z.number(),
    voltage: z.number(),
    consumption: z.number(),
  }),
  zigbee_vibration: $ReadingKey.extend({
    angle: z.number().nullish(),
    angle_x: z.number().nullish(),
    angle_y: z.number().nullish(),
    angle_z: z.number().nullish(),
    angle_x_absolute: z.number().nullish(),
    angle_y_absolute: z.number().nullish(),
    action: z.string().nullish(),
    battery: z.number(),
    voltage: z.number(),
  }),
  pms5003st: $ReadingKey.extend({
    cf_pm1: z.number(),
    cf_pm10: z.number(),
    cf_pm25: z.number(),
    pm1: z.number(),
    pm10: z.number(),
    pm25: z.number(),
    pm4: z.number().nullish(),
    pd05: z.number(),
    pd10: z.number(),
    pd25: z.number(),
    pd50: z.number(),
    pd100: z.number(),
    pd100g: z.number(),
    ch2o: z.number(),
    tmp: z.number(),
    rh: z.number(),
    pmv10: z.number(),
    pmv25: z.number(),
    pmv100: z.number(),
    pmv_total: z.number(),
    latitude: z.number().nullish(),
    longitude: z.number().nullish(),
  }),
  ptqs1005: $ReadingKey.extend({
    tvoc: z.number(),
    ch2o: z.number(),
    co2: z.number(),
    pm25: z.number(),
    tmp: z.number(),
    rh: z.number(),
    latitude: z.number().nullish(),
    longitude: z.number().nullish(),
  }),
  nemo_cloud: $ReadingKey.extend({
    battery: z.number().nullish(),
    ch2o: z.number().nullish(),
    tmp: z.number().nullish(),
    rh: z.number().nullish(),
    pressure: z.number().nullish(),
    co2: z.number().nullish(),
    lvoc: z.number().nullish(),
    pm1: z.number().nullish(),
    pm2_5: z.number().nullish(),
    pm4: z.number().nullish(),
    pm10: z.number().nullish(),
  }),
} as const;

export const $Reading = z.union([
  $Readings.nemo_cloud,
  $Readings.ptqs1005,
  $Readings.pms5003st,
  $Readings.zigbee_contact,
  $Readings.zigbee_temp,
  $Readings.zigbee_power,
  $Readings.zigbee_contact,
  $Readings.zigbee_occupancy,
]);
