import type {
  SensorMetricMetadata,
  SensorMetricName,
  SensorType,
} from "./types";

export const MetricsMetadata: {
  [T in SensorType]: SensorMetricMetadata<T, SensorMetricName<T>>[];
} = {
  nemo_cloud: [
    {
      name: "co2",
      displayName: "CO2",
      type: "number",
      unit: "ppm",
    },
    {
      name: "lvoc",
      displayName: "LVOC",
      type: "number",
      unit: "ppb",
    },
    { name: "pm1", displayName: "PM 1", type: "number", unit: "µg/m3" },
    { name: "pm2_5", displayName: "PM 2.5", type: "number", unit: "µg/m3" },
    { name: "pm4", displayName: "PM 4", type: "number", unit: "µg/m3" },
    { name: "pm10", displayName: "PM 10", type: "number", unit: "µg/m3" },
    { name: "pressure", displayName: "Pressure", type: "number", unit: "mb" },
    { name: "rh", displayName: "Humidity", type: "number", unit: "Rh%" },
    { name: "tmp", displayName: "Temperature", type: "number", unit: "°C" },
    {
      name: "ch2o",
      displayName: "CH2O",
      type: "number",
      unit: "mg/m3",
    },
    {
      name: "battery",
      displayName: "Battery",
      type: "number",
      unit: "V",
    },
  ],
  zigbee_temp: [
    {
      name: "temperature",
      displayName: "Temperature",
      type: "number",
      unit: "°C",
    },
    {
      name: "humidity",
      displayName: "Humidity",
      type: "number",
      unit: "Rh%",
    },
    {
      name: "battery",
      displayName: "Battery",
      type: "number",
      unit: "V",
    },
    {
      name: "voltage",
      displayName: "Voltage",
      type: "number",
      unit: "V",
    },
  ],
  zigbee_contact: [
    {
      name: "contact",
      displayName: "Contact",
      type: "boolean",
    },
    {
      name: "voltage",
      displayName: "Voltage",
      type: "number",
      unit: "V",
    },
    {
      name: "battery",
      displayName: "Battery",
      type: "number",
      unit: "V",
    },
  ],
  zigbee_occupancy: [
    {
      name: "occupancy",
      displayName: "Occupancy",
      type: "boolean",
    },
    {
      name: "illuminance",
      displayName: "Illuminance",
      type: "number",
    },
    {
      name: "battery",
      displayName: "Battery",
      type: "number",
      unit: "V",
    },
    {
      name: "voltage",
      displayName: "Voltage",
      type: "number",
      unit: "V",
    },
  ],
  zigbee_power: [
    { name: "power", displayName: "Power", type: "number", unit: "W" },
    { name: "consumption", displayName: "Consumption", type: "number" },
    { name: "state", displayName: "State", type: "string" },
    { name: "battery", displayName: "Battery", type: "number", unit: "V" },
    { name: "voltage", displayName: "Voltage", type: "number", unit: "V" },
  ],
  zigbee_vibration: [
    { name: "angle", displayName: "Angle", type: "number", unit: "°" },
    { name: "angle_x", displayName: "Angle X", type: "number", unit: "°" },
    {
      name: "angle_x_absolute",
      displayName: "Absolute Angle X",
      type: "number",
      unit: "°",
    },
    { name: "angle_y", displayName: "Angle Y", type: "number", unit: "°" },
    {
      name: "angle_y_absolute",
      displayName: "Absolute Angle Y",
      type: "number",
      unit: "°",
    },
    { name: "angle_z", displayName: "Angle Z", type: "number", unit: "°" },
    { name: "action", displayName: "Action", type: "string" },
    { name: "battery", displayName: "Battery", type: "number", unit: "V" },
    { name: "voltage", displayName: "Voltage", type: "number", unit: "V" },
  ],
  pms5003st: [
    { name: "cf_pm1", displayName: "CF PM 1", type: "number" },
    { name: "cf_pm10", displayName: "CF PM 10", type: "number" },
    { name: "cf_pm25", displayName: "CF PM 25", type: "number" },
    { name: "ch2o", displayName: "CH2O", type: "number", unit: "mg/m3" },
    { name: "pd05", displayName: "PD 5", type: "number" },
    { name: "pd10", displayName: "PD 10", type: "number" },
    { name: "pd25", displayName: "PD 25", type: "number" },
    { name: "pd50", displayName: "PD 5", type: "number" },
    { name: "pd100", displayName: "PD 100", type: "number" },
    { name: "pd100g", displayName: "PD 100g", type: "number" },
    { name: "pm1", displayName: "PM 1", type: "number", unit: "µg/m3" },
    { name: "pm10", displayName: "PM 10", type: "number", unit: "µg/m3" },
    { name: "pm25", displayName: "PM 2.5", type: "number", unit: "µg/m3" },
    { name: "pm4", displayName: "PM 4", type: "number", unit: "µg/m3" },
    { name: "pmv10", displayName: "PMV 10", type: "number", unit: "µg/m3" },
    { name: "pmv25", displayName: "PMV 2.5", type: "number", unit: "µg/m3" },
    { name: "pmv100", displayName: "PMV 100", type: "number", unit: "µg/m3" },
    {
      name: "pmv_total",
      displayName: "PMV Total",
      type: "number",
      unit: "µg/m3",
    },
    { name: "rh", displayName: "Humidity", type: "number", unit: "Rh%" },
    { name: "tmp", displayName: "Temperature", type: "number", unit: "°C" },
    { name: "latitude", displayName: "Latitude", type: "number", unit: "°" },
    { name: "longitude", displayName: "Longitude", type: "number", unit: "°" },
  ],
  ptqs1005: [
    { name: "rh", displayName: "Humidity", type: "number", unit: "Rh%" },
    { name: "tmp", displayName: "Temperature", type: "number", unit: "°C" },
    { name: "ch2o", displayName: "CH2O", type: "number", unit: "mg/m3" },
    { name: "co2", displayName: "CO2", type: "number", unit: "ppm" },
    { name: "pm25", displayName: "PM 2.5", type: "number", unit: "µg/m3" },
    { name: "tvoc", displayName: "TVOC", type: "number", unit: "ppm" },
    { name: "latitude", displayName: "Latitude", type: "number", unit: "°" },
    {
      name: "longitude",
      displayName: "Longitude",
      type: "number",
      unit: "°",
    },
  ],
};
